name: Run HexDrop

on:
    schedule:
      - cron: "0 13 * * *"
    workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-venv python3-dev python3-pip cron tzdata

      - name: Set up Python virtual environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Load secrets into environment
        run: |
          echo "DAILY_DEFAULT_EMAIL=${{ secrets.DAILY_DEFAULT_EMAIL }}" >> $GITHUB_ENV
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Run main.py
        run: |
          source env/bin/activate
          python3 main.py

      - name: Done
        run: echo "Cursecatcher script ran successfully at $(date)"
