name: Run HexDrop

on:
    schedule:
      - cron: "0 13 * * *"
    workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    env:
      BCC_LIST: ${{ vars.BCC_LIST }}

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-venv python3-dev python3-pip cron tzdata

      - name: Set up Python virtual environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Load secrets into environment
        run: |
          echo "DAILY_DEFAULT_EMAIL=${{ secrets.DAILY_DEFAULT_EMAIL }}" >> $GITHUB_ENV
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "BCC_LIST=${{ env.BCC_LIST }}" >> $GITHUB_ENV

      - name: Run main.py
        run: |
          source env/bin/activate
          python3 main.py

      - name: Commit and push updated report data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/*.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update report data"
            git push -u origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Done
        run: echo "Cursecatcher script ran successfully at $(date)"
